#!/bin/zsh
# Test script to demonstrate session behavior

echo "🧪 Session Behavior Test"
echo "========================"
echo ""

echo "📋 Test Setup Instructions:"
echo ""
echo "Open TWO terminal windows and follow along:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🟦 TERMINAL 1"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Create a test directory and session"
echo "mkdir -p /tmp/session-test"
echo "cd /tmp/session-test"
echo "sc"
echo ""
echo "# Type something unique"
echo "echo \"Terminal 1 was here at \$(date)\""
echo ""
echo "# Look at bottom status bar - what session name?"
echo "# Press: Ctrl+b then d (to detach)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🟩 TERMINAL 2"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Go to SAME directory"
echo "cd /tmp/session-test"
echo "sc"
echo ""
echo "# LOOK! You see \"Terminal 1 was here\"!"
echo "# This proves you're in the SAME session!"
echo ""
echo "# Type something"
echo "echo \"Terminal 2 is also here at \$(date)\""
echo ""
echo "# Press: Ctrl+b then d (to detach)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🟦 TERMINAL 1 (Again)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Now try DIFFERENT directory"
echo "mkdir -p /tmp/other-test"
echo "cd /tmp/other-test"
echo "sc"
echo ""
echo "# Look at status bar - different session name!"
echo "# No history from session-test!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 Verify with:"
echo ""
echo "sl"
echo ""
echo "You should see TWO sessions:"
echo "  - session-test"
echo "  - other-test"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎓 Lesson:"
echo "  - Same directory → Same session (shared view)"
echo "  - Different directory → Different session"
echo "  - Session name shown in bottom status bar"
echo ""
echo "🧹 Cleanup:"
echo "  sk session-test"
echo "  sk other-test"
echo "  rm -rf /tmp/session-test /tmp/other-test"
echo ""
