#!/bin/zsh
# Test script to verify Claude Code has separate conversations in different tmux sessions

echo "🧪 Claude Code Multi-Session Test"
echo "=================================="
echo ""
echo "This test will verify that each tmux session has its own Claude Code conversation."
echo ""
echo "📋 Instructions:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "SETUP: Open TWO terminal windows"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🟦 TERMINAL 1"
echo "─────────────"
echo ""
echo "cd ~/dotfiles"
echo "scs claude-test-1"
echo ""
echo "# You're now in session 'dotfiles-claude-test-1'"
echo "# Start Claude Code:"
echo ""
echo "claude"
echo ""
echo "# Ask Claude: \"What is 2 + 2? Remember this answer.\""
echo "# Claude will respond: 4"
echo ""
echo "# Exit Claude (Ctrl+D or type 'exit')"
echo "# Detach from tmux: Ctrl+b then d"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🟩 TERMINAL 2"
echo "─────────────"
echo ""
echo "cd ~/dotfiles"
echo "scs claude-test-2"
echo ""
echo "# You're now in session 'dotfiles-claude-test-2'"
echo "# Start Claude Code:"
echo ""
echo "claude"
echo ""
echo "# Ask Claude: \"What is 5 + 5? Remember this answer.\""
echo "# Claude will respond: 10"
echo ""
echo "# Exit Claude (Ctrl+D)"
echo "# Detach: Ctrl+b then d"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🟦 TERMINAL 1 (Return)"
echo "──────────────────────"
echo ""
echo "# Reconnect to first session:"
echo "ss"
echo "# Select 'dotfiles-claude-test-1'"
echo ""
echo "# Start Claude again:"
echo "claude"
echo ""
echo "# Ask: \"What answer did you remember for me?\""
echo "# Claude should say: 4 (from the first session!)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🟩 TERMINAL 2 (Return)"
echo "──────────────────────"
echo ""
echo "# Reconnect to second session:"
echo "ss"
echo "# Select 'dotfiles-claude-test-2'"
echo ""
echo "# Start Claude again:"
echo "claude"
echo ""
echo "# Ask: \"What answer did you remember for me?\""
echo "# Claude should say: 10 (from the second session!)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Expected Results:"
echo "────────────────────"
echo ""
echo "  Session 1 remembers: 4"
echo "  Session 2 remembers: 10"
echo ""
echo "  → Each session has its OWN conversation history!"
echo "  → They don't interfere with each other!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🧹 Cleanup:"
echo "───────────"
echo ""
echo "sk dotfiles-claude-test-1"
echo "sk dotfiles-claude-test-2"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Why This Matters:"
echo "────────────────────"
echo ""
echo "You can now:"
echo "  • Work on Feature A in session 1 with Claude"
echo "  • Work on Bug B in session 2 with Claude"
echo "  • Each has full context of THEIR conversation"
echo "  • Switch between them without losing context"
echo "  • No conversation cross-contamination!"
echo ""
