#!/usr/bin/env bash
# Enhanced Fish Shell Setup
# Installs powerful plugins and modern CLI tools

set -e

echo "🚀 Enhanced Fish Shell Setup"
echo "=============================="
echo ""

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check if fish is installed
if ! command_exists fish; then
    echo "❌ Fish shell not found. Please run ./install.sh first"
    exit 1
fi

echo "📦 Installing Modern CLI Tools..."
echo ""

# Core modern tools (highly recommended)
echo "Installing core tools: atuin, zoxide, bat, eza, fd, ripgrep..."
brew install atuin zoxide bat eza fd ripgrep git-delta

# AI tools
echo ""
echo "🤖 AI Tools Installation"
echo "========================"
echo ""
read -p "Install aichat (AI assistant)? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    brew install aichat
    echo "✅ aichat installed"
fi

echo ""
read -p "Install GitHub Copilot CLI (requires Copilot subscription)? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    npm install -g @githubnext/github-copilot-cli
    echo "✅ GitHub Copilot CLI installed"
    echo "   Run 'github-copilot-cli auth' to authenticate"
fi

# Optional: Starship prompt
echo ""
read -p "Install Starship prompt (alternative to tide)? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    brew install starship
    echo "✅ Starship installed"
fi

# Fisher plugins
echo ""
echo "📦 Installing Fish Plugins via Fisher..."
fish -c "
    # Install fisher if not already installed
    if not functions -q fisher
        curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source
        fisher install jorgebucaran/fisher
    end

    # Install enhanced plugins
    fisher install franciscolourenco/done                # Notifications
    fisher install jorgebucaran/autopair.fish            # Auto-close brackets
    fisher install patrickf1/colored-man-pages.fish      # Colored man pages
    fisher install edc/bass                              # Run bash scripts
    fisher install jhillyerd/plugin-git                  # Enhanced git

    echo '✅ Fisher plugins installed'
"

# Create enhanced configuration
echo ""
echo "🔧 Configuring Enhanced Tools..."

fish -c "
    # Backup existing config
    if test -f ~/.config/fish/conf.d/enhanced-tools.fish
        cp ~/.config/fish/conf.d/enhanced-tools.fish ~/.config/fish/conf.d/enhanced-tools.fish.backup
    end

    # Create enhanced tools configuration
    echo '# Enhanced Tools Configuration
# Auto-generated by install-enhanced.sh

# Atuin - Magical shell history
if command -v atuin >/dev/null 2>&1
    atuin init fish | source
end

# Zoxide - Smarter directory navigation
if command -v zoxide >/dev/null 2>&1
    zoxide init fish | source
end

# Starship prompt (if installed, comment out to use tide)
# if command -v starship >/dev/null 2>&1
#     starship init fish | source
# end

# Modern CLI tool aliases
if command -v bat >/dev/null 2>&1
    alias cat=\"bat --style=auto\"
    alias less=\"bat --paging=always\"
end

if command -v eza >/dev/null 2>&1
    alias ls=\"eza --icons\"
    alias ll=\"eza -la --icons --git\"
    alias tree=\"eza --tree --icons\"
    alias la=\"eza -a --icons\"
end

if command -v fd >/dev/null 2>&1
    alias find=\"fd\"
end

if command -v rg >/dev/null 2>&1
    alias grep=\"rg\"
end

# GitHub Copilot CLI aliases (if installed)
if command -v gh >/dev/null 2>&1; and gh copilot --version >/dev/null 2>&1
    alias \"??\"=\"gh copilot suggest -t shell\"
    alias \"git?\"=\"gh copilot suggest -t git\"
    alias \"explain\"=\"gh copilot explain\"
end

# AI assistant (if installed)
if command -v aichat >/dev/null 2>&1
    alias ai=\"aichat\"
end

# Done plugin configuration
set -U __done_min_cmd_duration 10000  # 10 seconds
set -U __done_notification_urgency_level normal

' > ~/.config/fish/conf.d/enhanced-tools.fish

    echo '✅ Enhanced configuration created'
"

# Configure git-delta
if command_exists delta; then
    echo ""
    echo "🎨 Configuring git-delta..."
    git config --global core.pager delta
    git config --global interactive.diffFilter "delta --color-only"
    git config --global delta.navigate true
    git config --global delta.side-by-side true
    git config --global delta.line-numbers true
    echo "✅ Git delta configured"
fi

echo ""
echo "🎉 Enhanced Setup Complete!"
echo ""
echo "🔥 New Features Available:"
echo "=========================="
echo ""
echo "📚 Better Commands:"
echo "   cat file.txt        → bat (syntax highlighted)"
echo "   ls                  → eza (with icons & git status)"
echo "   tree                → eza --tree"
echo "   find pattern        → fd (faster)"
echo "   grep pattern        → rg (ripgrep, much faster)"
echo ""
echo "🚀 Smarter Navigation:"
echo "   z dotfiles          → Jump to ~/dotfiles (learns habits)"
echo "   zi                  → Interactive directory jump"
echo "   Ctrl+R              → Atuin magical history search"
echo ""
echo "🤖 AI Features:"
if command_exists aichat; then
    echo "   ai 'your question'  → AI assistant"
fi
if command_exists gh && gh copilot --version >/dev/null 2>&1; then
    echo "   ?? 'description'    → AI suggests shell command"
    echo "   git? 'description'  → AI suggests git command"
    echo "   explain 'command'   → AI explains command"
fi
echo ""
echo "🔔 Productivity:"
echo "   Long commands       → Get notification when done"
echo "   Man pages           → Now syntax highlighted"
echo "   Brackets            → Auto-close automatically"
echo ""
echo "📊 Try These:"
echo "   atuin stats         → View command statistics"
echo "   ll                  → Better ls with git status"
echo "   tree -L 3           → Tree view"
if command_exists gh && gh copilot --version >/dev/null 2>&1; then
    echo "   ?? find large files → AI command suggestion"
fi
echo ""
echo "💡 Tips:"
echo "   - Restart fish or run 'exec fish' to reload config"
echo "   - Atuin syncs history across machines (encrypted)"
echo "   - Zoxide learns your most-used directories"
if command_exists gh && gh copilot --version >/dev/null 2>&1; then
    echo "   - Run 'github-copilot-cli auth' to enable Copilot"
fi
echo ""
echo "📖 Full documentation: ~/dotfiles/fish/ADVANCED_PLUGINS.md"
echo ""
