name: opencode

on:
  issue_comment:
    types: [created]

jobs:
  opencode:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /opencode') ||
      startsWith(github.event.comment.body, '/opencode')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install OpenCode
        run: npm install -g opencode-ai@latest

      - name: Run OpenCode
        env:
          GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODEL: google/gemini-2.0-flash
          REPO: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          COMMENT_ID: ${{ github.event.comment.id }}
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          echo "OpenCode version:"
          opencode --version
          
          # Extract the command from the comment
          COMMAND=$(echo "$COMMENT_BODY" | grep -oE '(/oc |/opencode ).*' | sed 's/^\/[^ ]* //')
          echo "Command: $COMMAND"
          
          # Get response from OpenCode and clean ANSI codes
          echo "Getting AI response..."
          # Capture only stdout, remove ANSI codes, and deduplicate consecutive identical lines
          RESPONSE=$(opencode run "$COMMAND" --model "$MODEL" 2>/dev/null | sed 's/\x1b\[[0-9;]*m//g' | uniq || echo "Error: Could not get response")
          
          echo "Response: $RESPONSE"
          
          # Post response back to GitHub issue
          if [ -n "$RESPONSE" ]; then
            # Get current timestamp
            TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
            
            cat > comment.md << EOF
          ## 🤖 OpenCode Response
          
          > **Query**: $COMMAND
          
          ### 💬 Answer
          
          $RESPONSE
          
          ---
          
          <details>
          <summary>📊 Response Details</summary>
          
          - **Model**: \`$MODEL\` 
          - **Timestamp**: $TIMESTAMP
          - **Workflow Run**: [#${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          - **Triggered by**: @${{ github.actor }}
          
          </details>
          
          ---
          
          <div align="center">
          
          ✨ **Powered by [OpenCode](https://opencode.ai) with Google Gemini** ✨
          
          </div>
          EOF
            gh issue comment "$ISSUE_NUMBER" --body-file comment.md
          else
            echo "❌ No response generated"
            gh issue comment "$ISSUE_NUMBER" --body "## ❌ OpenCode Error
          
          Unable to generate a response for your query. Please check:
          - The API key is configured correctly
          - The model is available
          - Your query is properly formatted
          
          **Debug Info**: Check [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          fi